### ISSUE TITLE
How is living in Buenos Aires?

### ISSUE THREAD

**Issue by gpbl** [bevacqua/ama#1]
Sometimes I think to move to South America, and I'm often considering Argentina as a possible destination (just because Argentina seems similar to Italy :relaxed:). 

Do you think BA is a good place to start as senior web developer? Are you happy living there? Are there other smaller cities for someone preferring a less chaotic lifestyle?

Thanks :)

**Comment by bevacqua** [comment]
BA is great!

It's has great food just like Italy (and ice cream -- Italy was probably the only other country where I felt like "oh okay I can eat this ice cream"), some nice startups, a few of the big companies, awesome night life, and the city is actually quite comparable with other big cities.

Sure, it's not Bologna's food and it's not Paris (although we tried hard to copy them), but when you factor in how cheap it is, I think it's a great place to live.
