### ISSUE TITLE
Recommended books on Web Development and Javascript

### ISSUE THREAD

**Issue by audiolion** [bevacqua/ama#6]
Hey bevacua I wanted to ask you, today, what a curated list of books on web development and on javascript might be that you would recommend.

Interests are in writing and building applications in JS, books on node, general web dev related, ui/ux, etc.

**Comment by bevacqua** [comment]
See https://github.com/bevacqua/reads

**Comment by audiolion** [comment]
Hey, sorry for not being more explicit, I was asking in specific because you only have 2 js books listed, Eloquent Javascript which you haven't started/reviewed and Javascript: The Good Parts which you read but gave it a neutral rating. I was just wondering if there were any others.

What about the book you wrote! :)

**Comment by bevacqua** [comment]
That's pretty much the only book I've read on JavaScript, (good parts)
Definitely check out my book, obviously, haha :tada:
